language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-external-libs
  - PLATFORMIO_PROJECT_DIR=examples/arduino-internal-libs
  - PLATFORMIO_PROJECT_DIR=examples/arduino-mxchip-azureiot
  - PLATFORMIO_PROJECT_DIR=examples/arduino-mxchip-filesystem
  - PLATFORMIO_PROJECT_DIR=examples/arduino-mxchip-sensors
  - PLATFORMIO_PROJECT_DIR=examples/arduino-mxchip-wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/cmsis-blink
  - PLATFORMIO_PROJECT_DIR=examples/libopencm3-1bitsy
  - PLATFORMIO_PROJECT_DIR=examples/libopencm3-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-blink
  - PLATFORMIO_PROJECT_DIR=examples/mbed-custom-target
  - PLATFORMIO_PROJECT_DIR=examples/mbed-dsp PLATFORMIO_BUILD_FLAGS="-fno-strict-aliasing"
  - PLATFORMIO_PROJECT_DIR=examples/mbed-events
  - PLATFORMIO_PROJECT_DIR=examples/mbed-filesystem
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-ethernet
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-ethernet-tls
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-semaphore
  - PLATFORMIO_PROJECT_DIR=examples/mbed-rtos-mesh-minimal
  - PLATFORMIO_PROJECT_DIR=examples/mbed-serial
  - PLATFORMIO_PROJECT_DIR=examples/spl-blink
  - PLATFORMIO_PROJECT_DIR=examples/stm32cube-hal-blink
  - PLATFORMIO_PROJECT_DIR=examples/stm32cube-ll-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-cpp-synchronization
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-drivers-can
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-net-https-client
  - PLATFORMIO_PROJECT_DIR=examples/zephyr-subsys-usb-hid-mouse

# Zephyr framework doesn't support python 2
jobs:
  exclude:
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-blink
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-cpp-synchronization
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-drivers-can
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-net-https-client
    - python: "2.7"
      env: PLATFORMIO_PROJECT_DIR=examples/zephyr-subsys-usb-hid-mouse
  

install:
  - pip install -U https://github.com/platformio/platformio/archive/develop.zip
  - platformio platform install file://.

script:
  - platformio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
