name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  UPLOAD_BUILD: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'OS-Q/P21'
    strategy:
      fail-fast: true
      matrix:
        examples:
          - "arduino-blink"
          - "cmsis-blink"
          - "libopencm3-blink"
          - "spl-blink"
          - "stm32cube-hal-blink"
          - "stm32cube-ll-blink"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
        qio platform install file://.

    - name: Build
      run: |
        qio run -d examples/${{ matrix.examples }}

  release:
    needs:
      - build
    if: success() && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Generate tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "::set-output name=release_tag::release_package_$(date +"%Y.%m.%d")_${GITHUB_REF/refs\/tags\//}"
          echo "::set-output name=status::success"

      - name: Package Src
        id: package
        run: |
          echo "Platform P21 for STM32 MCU" >> README.txt
          echo $(date +"%Y.%m.%d") >> README.txt
          echo ${GITHUB_REF/refs\/tags\//} >> README.txt
          echo -e "www.OS-Q.com\n" >> README.txt
          git log --stat -1 >> README.txt
          zip -r P21.zip misc ldscripts boards extend link.json link.py
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload Firmware
        if: steps.package.outputs.status == 'success' &&  env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: P21
          path: ${{ env.FIRMWARE }}/P21.zip

      - name: Upload Release
        id: upload-release
        uses: stopstopstop/release-action@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        env:
          GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            ${{ env.FIRMWARE }}/P21.zip
            ${{ env.FIRMWARE }}/README.txt

      - name: Setup OSS
        uses: stopstopstop/ossutil-action@master
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Upload To OSS
        id: OSS
        run: |
          ossutil cp ${{ env.FIRMWARE }}/P21.zip ${{ secrets.OSS_BUCKET }} -rf
          echo "::set-output name=status::success"


  rebuild:
    needs:
      - release
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        id: getgh
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          pio platform install https://github.com/OS-Q/P21/releases/latest/download/P21.zip
          echo "::set-output name=status::success"

      - name: ReBuild
        id: rebuild
        if: steps.getgh.outputs.status == 'success' && !cancelled()
        run: |
          qio run -d examples/cmsis-blink
          qio run -d examples/arduino-blink
          qio run -d examples/spl-blink
          qio run -d examples/stm32cube-hal-blink
          qio run -d examples/libopencm3-blink
          echo "::set-output name=status::success"

      - name: Send Mail
        if: steps.rebuild.outputs.status == 'success' && !cancelled()
        uses: stopstopstop/mail-action@master
        with:
          server_address:  smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: OS-Q P21 Released
          to: ${{secrets.MAIL_TO}}
          from: Qitas
          cc: ${{github.event.pusher.email}}
          content_type: text/html
          convert_markdown: true
          body: file://README.md

      - name: notification
        uses: stopstopstop/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: ${{steps.rebuild.outputs.status}}
