name: CI

on:
  push:
    branches:
<<<<<<< HEAD:.github/workflows/CI.yml
      - master
      - main
    paths:
      - 'boards/**'
      - 'builder/**'
      - 'extend/**'
      - 'examples/**'
      - '**.json'
      - '**.py'
=======
      - pio
    paths:
      - 'boards/**'
      - 'misc/**'
      - 'builder/**'
      - 'ldscripts/**'
      - 'examples/**'
      - 'platform.json'
      - 'platform.py'
>>>>>>> pio:.github/workflows/PIO.yml

env:
  UPLOAD_BUILD: true

jobs:
  CodeCheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        enable: all #performance,portability,warning
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        std: c11
        output_file: ./codecheck.txt
        other_options: --bug-hunting --verbose --std=c11

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code_check_report
        path: codecheck.txt

  QIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "arduino-external-libs"
          - "arduino-internal-libs"
          - "arduino-mbed-doom"
          - "arduino-mbed-rpc"
          - "arduino-mxchip-azureiot"
          - "arduino-mxchip-filesystem"
          - "arduino-mxchip-sensors"
          - "arduino-mxchip-wifiscan"
          - "cmsis-blink"
          - "mbed-rtos-blink-baremetal"
          - "mbed-rtos-custom-target"
          - "mbed-rtos-ethernet-tls"
          - "mbed-rtos-events"
          - "mbed-rtos-filesystem"
          - "mbed-rtos-mesh-minimal"
          - "mbed-rtos-serial"
          - "mbed-rtos-usb-keyboard"
          - "mbed-rtos-wifi"
          - "mbed-blink"
          - "mbed-custom-target"
          - "mbed-dsp"
          - "mbed-events"
          - "mbed-filesystem"
          - "mbed-rtos"
          - "mbed-rtos-ethernet-tls"
          - "mbed-rtos-mesh-minimal"
          - "mbed-serial"
          - "spl-blink"
          - "stm32cube-hal-blink"
          - "stm32cube-hal-eeprom-emulation"
          - "stm32cube-hal-extmem-boot"
          - "stm32cube-hal-iap"
          - "stm32cube-hal-lcd"
          - "stm32cube-hal-usb-device-dfu"
          - "stm32cube-hal-wifi-client"
          - "stm32cube-ll-blink"

        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install QIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          pio platform install file://.

      - name: Build examples
        id: build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: qio_ci_build_${{ matrix.example }}_${{ matrix.os }}
          path: examples/${{ matrix.example }}/.pio/build/

  QIO_fail:
    needs:
      - QIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "QIO CI failure"

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "arduino-blink"
          - "arduino-external-libs"
          - "arduino-internal-libs"
          - "arduino-mbed-doom"
          - "arduino-mbed-rpc"
          - "arduino-mxchip-azureiot"
          - "arduino-mxchip-filesystem"
          - "arduino-mxchip-sensors"
          - "arduino-mxchip-wifiscan"
          - "cmsis-blink"
          - "mbed-rtos-blink-baremetal"
          - "mbed-rtos-custom-target"
          - "mbed-rtos-ethernet-tls"
          - "mbed-rtos-events"
          - "mbed-rtos-filesystem"
          - "mbed-rtos-mesh-minimal"
          - "mbed-rtos-serial"
          - "mbed-rtos-usb-keyboard"
          - "mbed-rtos-wifi"
          - "mbed-blink"
          - "mbed-custom-target"
          - "mbed-dsp"
          - "mbed-events"
          - "mbed-filesystem"
          - "mbed-rtos"
          - "mbed-rtos-ethernet-tls"
          - "mbed-rtos-mesh-minimal"
          - "mbed-serial"
          - "spl-blink"
          - "stm32cube-hal-blink"
          - "stm32cube-hal-eeprom-emulation"
          - "stm32cube-hal-extmem-boot"
          - "stm32cube-hal-iap"
          - "stm32cube-hal-lcd"
          - "stm32cube-hal-usb-device-dfu"
          - "stm32cube-hal-wifi-client"
          - "stm32cube-ll-blink"
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PIO
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Build examples
        id: build
        if: success()
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}
<<<<<<< HEAD:.github/workflows/CI.yml
=======
          echo "::set-output name=status::success"
>>>>>>> pio:.github/workflows/PIO.yml

      - name: Upload
        if: env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
<<<<<<< HEAD:.github/workflows/CI.yml
          name: pio_ci_build_${{ matrix.example }}_${{ matrix.os }}
          path: examples/${{ matrix.example }}/.pio/build/
=======
          name: pio_${{ matrix.example }}_${{ matrix.os }}
          path: examples/${{ matrix.example }}/.pio/build
>>>>>>> pio:.github/workflows/PIO.yml

  PIO_fail:
    needs:
      - PIO
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{github.repository}}/${{github.workflow}}
          message: "PIO CI failure"
