name: ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        examples:
          - "examples/arduino-blink"
          - "examples/cmsis-blink"
          - "examples/libopencm3-blink"
          - "examples/mbed-rtos-blink-baremetal"
          - "examples/mbed-blink"
          - "examples/spl-blink"
          - "examples/stm32cube-hal-blink"
          - "examples/stm32cube-ll-blink"
          - "examples/zephyr-blink"
          - "tests/arduino-blink-different-cores"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          pip3 install adafruit-nrfutil uritemplate requests intelhex
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          platformio platform install file://.

      - name: Build
        run: |
          platformio run -d ${{ matrix.examples }}

      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-build-P21
          path: ${{ matrix.examples }}/build
